global using Iot.Device.DhcpServer;
global using nanoFramework.Networking;
global using nanoFramework.Runtime.Native;
global using System;
global using System.Device.Gpio;
global using System.Diagnostics;
global using System.Net;
global using System.Net.NetworkInformation;
global using System.Threading;
global using AuthenticationType = System.Net.NetworkInformation.AuthenticationType;
global using System.Collections;
global using System.IO;
global using Iot.Device.ServoMotor;
global using nanoFramework.Hardware.Esp32;
global using System.Device.Pwm;
